name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t bot0:${{ github.run_number }} .

    - name: Copy Source to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/deploy-user/Bot-Creator/projects/bot0"

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/deploy-user/Bot-Creator/projects/bot0
          rm -rf ./*
          docker build -t bot0:${{ github.run_number }} .
          docker run -d bot0:${{ github.run_number }}
